### ISSUE TITLE
new user issue palazzetti idro 18

### ISSUE THREAD

**Issue by Skymer83** [Vost3/hass-palazzetti#11]
Hi, sorry 4 my english.
i have a problem in compile configuration.yaml, IP not work 
i created folder like you explain, but not work.
 i need some help please i'm noob!! 
ty

**Comment by rul3zz** [comment]
Same here.
Think there's no more support for this integration

**Comment by Skymer83** [comment]
😭😭😭this is a very good integration but need little changes that i not
know how to do.. sorry 4 my english

Il Mer 2 Feb 2022, 17:59 rul3zz ***@***.***> ha scritto:

**Comment by Vost3** [comment]
Hi
Are you ping your connexion box ? 
Be sure your connexion box is online. 
Could you access of the web interface in your browser ?

Don"t hesitate ;)

**Comment by Skymer83** [comment]
Hi! Sorry for my english.
I need time to try because the project has been left suspended ... I'm
weating for new raspberry in december.
I can explain my project...
I have a palazzetti fireplace that works on an ambient probe.
I have all the NETATMO valves on the radiators, I would like to create an
automatism whereby if the fireplace has water at 50° then the valves open
to maximum water flow, while if the fireplace is off the valves follow
their normal netatmo programming .
I hope I made myself clear
Can you help me?
Thanks

Il Lun 14 Nov 2022, 20:45 Steve Vogel ***@***.***> ha scritto:

**Comment by Vost3** [comment]
No news
