### ISSUE TITLE
Giorgia

### ISSUE THREAD

**Issue by meyxiam** [Vost3/hass-palazzetti#18]
Bonjour,

Je débute sous Home Assistant et je cherche à ajouter mon poêle Palazzetti Giorgia à mon HA (j'ai bien trouvé l'IP de ma connection box)
Mais j'ai du mal à comprendre ce que je dois mettre dans le fichier configuration.yaml (ou comment le découper en plusieurs fichiers).
En effet dans la documentation, il y a 2 parties "Configuration configuration.yaml"
Et pour les autres parties, je n'ai pas encore tout compris.

Merci d'avance pour votre aide.
Cordialement

**Comment by Samquad** [comment]
Moi j'ai mis ça dans le configuration.yaml:

sensor: !include sensor.yaml

#############################################
#               Palazetti                   #
#############################################
palazzetti:
  ip: 192.168.1.XXX

input_text:
  text_test:
    name: Text Test
#############################################
#                 Switch                    #
#############################################
switch:
  - platform: template
    switches:
      #############################################
      #                 palazzetti                #
      #############################################
      # State
      stove_status:
        friendly_name: "État"        
        value_template: "{{ state_attr('palazzetti.stove', 'STATUS') | int > 0 and state_attr('palazzetti.stove', 'STATUS') | int != 10 }}"
        turn_on:
          service: palazzetti.set_parms
          data:
            STATUS: 'on'
        turn_off:
          service: palazzetti.set_parms
          data:
            STATUS: 'off'
        icon_template: >-
          {% if state_attr('palazzetti.stove', 'STATUS') | int > 0 %}
            mdi:fireplace
          {% else %}
            mdi:fireplace-off
          {% endif %}  

input_number:
  # Fan level
  stove_fan_lvl:
    name: "Ventilation"
    min: 0
    max: 7
    step: 1
    icon : mdi:fan

          
  #Fire level
  stove_fire_lvl:
    name: "Puissance"
    initial: 1
    min: 1
    max: 5
    step: 1
    icon: mdi:fire

_________________________________________________
ensuite si tu n'as pas le fichier sensor.yaml tu le créés si il existe tu ajoutes les capteurs que tu veux récupérer:

#############################################
#               Palazetti                   #
#############################################

- platform: template
  sensors:
    stove_temperature_poele:
      friendly_name: Temperature Poele
      value_template: "{{ state_attr('palazzetti.stove', 'T1') | float }}"
      icon_template: mdi:thermometer
      unit_of_measurement: °C

- platform: template
  sensors:
    stove_temperature_ballon:
      friendly_name: Temperature Ballon
      value_template: "{{ state_attr('palazzetti.stove', 'T5') | float }}"
      icon_template: mdi:thermometer
      unit_of_measurement: °C

- platform: template
  sensors:
    stove_conso_pellets:
      friendly_name: Consommation Pellets
      value_template: "{{ state_attr('palazzetti.stove', 'PQT') | int }}"
      icon_template: mdi:counter
      unit_of_measurement: Kg

___________________________________________________________________________________
importer les automations dans le fichier automations.yaml

- id: '1'
  alias: Check pwr state
  trigger:
    platform: state
    entity_id: palazzetti.stove
  action:
  - service: input_text.set_value    
    data_template:
      entity_id: input_text.text_test # don't miss to create a input_text "text_test" for test this script
      value: "{{ state_attr('palazzetti.stove', 'PWR') }}"

- id: '2'
  alias: Stove Fan State change
  trigger:
    platform: state
    entity_id: input_number.stove_fan_lvl
  action:
    service: palazzetti.set_parms
    data_template:
      RFAN: "{{ states('input_number.stove_fan_lvl') | int }}"

- id: '3'
  alias: Stove Fire State change
  trigger:
    platform: state
    entity_id: input_number.stove_fire_lvl
  action:
    service: palazzetti.set_parms
    data_template:
      PWR: "{{ states('input_number.stove_fire_lvl') | int }}"

- id: '4'
  alias: Stove Fan State check
  trigger:
    platform: state
    entity_id: palazzetti.f2l
  action:
    service: input_number.set_value
    data:
      entity_id: input_number.stove_fan_lvl
      value: "{{ states('palazzetti.f2l') }}"

- id: '5'
  alias: Stove Fire State check
  trigger:
    platform: state
    entity_id: palazzetti.pwr
  action:
    service: input_number.set_value
    data:
      entity_id: input_number.stove_fire_lvl
      value: "{{ states('palazzetti.pwr') }}"

___________________________________________________________

tu vérifies la conf et tu redémarres et les capeurs devraient s'importer automatiquement

**Comment by meyxiam** [comment]
@Samquad  Excuses-moi mais il y a certaines balises qui sont interprétées par le site et du coup ça reste compliqué à bien identifier ce qu'il faut faire lorsqu'on est noob. Tu pourrais modifier ton message pour le rendre parfaitement lisible pour toute la communauté stp. Merci d'avance.

**Comment by meyxiam** [comment]
j'ai fini par réussir. Voici mes infos dans le configuration.xml avec la bonne indentation en format image
![image](https://github.com/Vost3/hass-palazzetti/assets/155761793/e80cc15b-a12f-476f-8fc6-3b43eb689524)
